pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
               dir('bugtracker-backend') {
                   bat 'go test ./... -v'
               }
            }
        }
        stage('Unit Tests - Frontend'){
            steps {
                dir('bugtracker-frontend'){
                    bat '''
                    call npm ci
                    call npm test
                    '''
                }
            }
            post {
                always {
                    junit 'backtracker-frontend/test-results.xml'

                }
            }
        }
    }
}