pipeline {
    #agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker{
                   image 'snakee/golang-junit:1.21' 
                   reuseNode true
                }
            environment {
                // Redirect the Go cache to the local workspace
                GOCACHE = "${env.WORKSPACE}/.cache"
                }
            }
            steps {
               dir('bugtracker-backend') {
                   sh 'go test ./... -v'
               }
            }
        }
    }
}